# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class CliExampleAT015 < Formula
  desc ""
  homepage "https://github.com/ThibautRobinet/cli-example"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ThibautRobinet/cli-example/releases/download/v0.1.6/cli-example_0.1.6_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e11a5c335c3c2e3316c06f932930c51abddc9bb14aa73568b594f023afde9f78"

      def install
        bin.install "cli-example"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ThibautRobinet/cli-example/releases/download/v0.1.6/cli-example_0.1.6_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "0a6ce8076f021cfec6463b7ec85c2e252136256bf945f4c7c8542de98c8a58bc"

      def install
        bin.install "cli-example"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ThibautRobinet/cli-example/releases/download/v0.1.6/cli-example_0.1.6_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f6daffc3a5704ff1ca46257e2a2ca9c1966070b02dd7aeec93366184547b8c66"

      def install
        bin.install "cli-example"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ThibautRobinet/cli-example/releases/download/v0.1.6/cli-example_0.1.6_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "21209ba65927f799176073eebd0f4c9628d32a359e1f221807c05f139b03a781"

      def install
        bin.install "cli-example"
      end
    end
  end
end
