# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class CliExample < Formula
  desc ""
  homepage "https://github.com/ThibautRobinet/cli-example"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ThibautRobinet/cli-example/releases/download/v0.1.1/cli-example_0.1.1_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "80bae6a8a54a238a5ce7550ae016d5f464bff6b085ce98ccdaf368ee5e37c7d7"

      def install
        bin.install "cli-example"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ThibautRobinet/cli-example/releases/download/v0.1.1/cli-example_0.1.1_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1632a1265de6f420c677154a678f750a5ae20c1f562343f7ae4937bc55402a34"

      def install
        bin.install "cli-example"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ThibautRobinet/cli-example/releases/download/v0.1.1/cli-example_0.1.1_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7c70402cfb8390c92736596dea328dd75e63272a523309be4e0e918717085e16"

      def install
        bin.install "cli-example"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ThibautRobinet/cli-example/releases/download/v0.1.1/cli-example_0.1.1_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "683ecbb593e784ba696eb162f6a4447fa0712c74c8b747f8c99790d38589b239"

      def install
        bin.install "cli-example"
      end
    end
  end
end
