# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class NameAT014 < Formula
  desc ""
  homepage "https://github.com/ThibautRobinet/cli-example"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ThibautRobinet/cli-example/releases/download/v0.1.4/cli-example_0.1.4_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d952cc652f4500f6a94d33f61fdd77a4869a5fbeb021b70622d990ff9a2674ad"

      def install
        bin.install "cli-example"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ThibautRobinet/cli-example/releases/download/v0.1.4/cli-example_0.1.4_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7e1251bdba2a516b7a2e2eda7e9854d22fe53853c71bad347f3182c1ddb0b221"

      def install
        bin.install "cli-example"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ThibautRobinet/cli-example/releases/download/v0.1.4/cli-example_0.1.4_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "533b8a7cb677dd7409e14d64b102219a22f66949faf07458ee0ec9a04d4c85dd"

      def install
        bin.install "cli-example"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ThibautRobinet/cli-example/releases/download/v0.1.4/cli-example_0.1.4_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "3c932c2a919bb63540c32f41500e73a882c19158841018c09bb6011b3ea9b5a8"

      def install
        bin.install "cli-example"
      end
    end
  end
end
