# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class NameAT012 < Formula
  desc ""
  homepage "https://github.com/ThibautRobinet/cli-example"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ThibautRobinet/cli-example/releases/download/v0.1.2/cli-example_0.1.2_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d4dec645b5ba9b2fdf06acb120c702f9576efa2505683cd7ef39bf813bda0b78"

      def install
        bin.install "cli-example"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ThibautRobinet/cli-example/releases/download/v0.1.2/cli-example_0.1.2_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5204edb53b55fbbe57fa8f86e78b53bd5c88943f1fae214418e3efe36c0caffc"

      def install
        bin.install "cli-example"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ThibautRobinet/cli-example/releases/download/v0.1.2/cli-example_0.1.2_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "afb2d59621701cd5e235acf38a81a4f1deb99210be6fe40162603980d7705b6b"

      def install
        bin.install "cli-example"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ThibautRobinet/cli-example/releases/download/v0.1.2/cli-example_0.1.2_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "dc7527c103fcb56b858c1a239a94cc396dddde88d157ef6525da2d7d2f40f5ad"

      def install
        bin.install "cli-example"
      end
    end
  end
end
