# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "download_strategy"
class NameAT013 < Formula
  desc ""
  homepage "https://github.com/ThibautRobinet/cli-example"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ThibautRobinet/cli-example/releases/download/v0.1.3/cli-example_0.1.3_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "36bc77e2c8aeafc21129430c27292293f6384dc23e02d79f92d4f4037bb06d2f"

      def install
        bin.install "cli-example"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ThibautRobinet/cli-example/releases/download/v0.1.3/cli-example_0.1.3_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d7e8efa052c5838caa37b4a971d2f7d99f6f9630a77b81904f73a6c589add55f"

      def install
        bin.install "cli-example"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ThibautRobinet/cli-example/releases/download/v0.1.3/cli-example_0.1.3_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "91345d1c6ad951ac0a0b572df9c4688248318b08abaa08e4dd81514b147acca0"

      def install
        bin.install "cli-example"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ThibautRobinet/cli-example/releases/download/v0.1.3/cli-example_0.1.3_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ffb79c315694dd85c8ab74dc93f65c31e6914a312c33fe13e9e00d45bae7776e"

      def install
        bin.install "cli-example"
      end
    end
  end
end
